# @package _group_
_target_: src.models.BertForMaskedLanguageModeling
model_type: transformer
task: masked_language_modeling
model_config_file: "/home/gridsan/groups/ai4bio_shared/models/in_house/bert_configs/bert/config.json"
lr: 1e-5
warmup_steps: 10000
