
name: antibody_design
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Required Dependencies
  - python=3.8.*
  - pytorch=1.8.0
  - pytorch-lightning=1.0.* # Minor changes might be needed for a later version of the pytorch ligthning library. 
  - pyyaml=5.3.1
  - torchvision
  - scikit-learn=0.24.1
  - pandas
  - tqdm
  - pip
  - pip:
    - tape-proteins==0.5
    - gpytorch==1.4.1
    - hydra-core>=1.0
    - hydra-submitit-launcher>=1.0
    - seaborn
    - onnx
    - onnxruntime
