name: biotransfer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Required Dependencies
  - python=3.8.*
  - pip=21.1.1
  - cudatoolkit=10.1.243
  - torchvision
  - pytorch
  - pip:
    - tape-proteins==0.4
    - gpytorch==1.2.0
    - pytorch-lightning==1.0.0
    - hydra-core==1.1.0.dev7
    - hydra-submitit-launcher==1.1.5
    - hydra-optuna-sweeper==0.9.0rc2
    - optuna==2.5.0
    - tqdm
    - scikit-learn
    - pandas
    - psycopg2-binary

