defaults:
    - logger_cfgs: Tensorboard
    #- override hydra/launcher: submitit_slurm

experiment_name: "eval_finetune_14H"
nodes: 1
strict_reload: True 
reload_checkpoint_path: /home/gridsan/LI25662/ML4Bio/biotransfer/results/train_titration_14H_HC/train_14H_finetune_all_LC/2021-08-31/15-51-24/8/checkpoint-v0.ckpt

hydra:
    run:
        dir: ./results/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
############

model_cfg:
    _target_: src.models.BertForValuePrediction
    downstream_dropout: 0.1
    downstream_hid_dim: 512
    lr: 2.79551209035589e-05
    loss_function: mse
    model_config_file: /home/gridsan/groups/ai4bio_shared/models/in_house/bert_configs/bert/config.json
    warmup_steps: 10000

trainer_cfg:
    max_epochs: 5000
    gpus: 2
    num_nodes: ${nodes}
    distributed_backend: ddp
    #train_percent_check: 0.1

eval_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: test
    chain: 14H
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median
    
eval_dataloader_cfg:
    batch_size: 32
    shuffle: True
