defaults:
    - logger_cfgs: Tensorboard
    #- override hydra/launcher: submitit_slurm

experiment_name: "eval_finetune_14L"
nodes: 1
strict_reload: True
reload_checkpoint_path: <Path to model checkpoint>

hydra:
    run:
        dir: ./results/${now:%Y-%m-%d}/${now:%H-%M-%S}
############

model_cfg:
    _target_: src.models.BertForValuePrediction
    downstream_dropout: 0.1
    downstream_hid_dim: 512
    lr: 2.79551209035589e-05
    loss_function: mse
    model_config_file: <Full Path>/biotransfer/pretrained_models/bert_configs/config.json # full path to the bert config file
    warmup_steps: 10000

trainer_cfg:
    max_epochs: 100
    gpus: 2
    num_nodes: ${nodes}
    distributed_backend: ddp
    #train_percent_check: 0.1

eval_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: <Full Path>/biotransfer/data/covid/
    split: test
    chain: 14L
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median
    
eval_dataloader_cfg:
    batch_size: 32
    shuffle: True
