# @package _group_
_target_: src.models.CNN
_recursive_: False
enc_channels: [30, 32, 64]
enc_kernel_sizes: [5, 5]
enc_strides: [1, 1]
enc_paddings: [0, 0]

enc_hidden_sizes: [128, 16]
mp_kernel_size: 2
mp_stride: 2
dropout: .15
verbose: False
optimizer_cfg:
    _target_: torch.optim.Adam
    lr: .001