defaults:
    - model_cfg: CNN
    - logger_cfgs: Tensorboard
    #- override hydra/launcher: submitit_slurm

experiment_name: "eval_cnn_IgG"
strict_reload: True
reload_checkpoint_path: <Path to model checkpoint>

hydra:
    run:
        dir: ./results/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
##########

trainer_cfg:
    max_epochs: 1
    gpus: 2
    num_nodes: 1
    distributed_backend: ddp

  
eval_set_cfg:
    _target_: src.datasets.GiffordDataset
    data_path: /home/li25662/AIforGreatGood/biotransfer/data/IgG/rep1_rep2_splits
    split: test
    in_memory: False
    collate_type: full_padded
    token_encode_type: one_hot
    
eval_dataloader_cfg:
    batch_size: 32

