defaults:
    - model_cfg: ExactGP
    #- logger_cfgs: Tensorboard
    - override hydra/launcher: submitit_slurm
    - override hydra/sweeper: optuna

experiment_name: "eval_exact_gp_template"
nodes: 1
strict_reload: True
reload_state_dict_path: "/home/gridsan/groups/ai4bio_shared/models/in_house/hyperparam_sweep/14H/GP/GP_model_state_dict.pth"
pca_model_path: "/home/gridsan/groups/ai4bio_shared/models/in_house/hyperparam_sweep/14H/GP/pca_model.sav"

hydra:
    run:
        dir: ./results/train/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

    sweep:
        dir: ./results/train/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

    launcher:
        partition: gaia
        tasks_per_node: 1
        nodes: ${nodes}
        constraint: xeon-g6
        timeout_min: 10000
        additional_parameters:
            {'gres':'gpu:volta:1'}
############
feat_cfg:
    _target_: src.models.feat_extraction.BertFeatExtractor
    model_config_file: /home/gridsan/groups/ai4bio_shared/models/in_house/bert/config.json
    feat_path: "/home/gridsan/groups/ai4bio_shared/models/in_house/heavychain_initialized_by_pfam_batchsize_2048_layers_24_lr_1e-5_hidsize_1024_intermediatesize_4096_attentionheads_16_epoch_5.ckpt"
    strict_reload: False
    variable_regions: True

train_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: train
    chain: 14H
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median

train_dataloader_cfg:
    batch_size: 64

val_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: valid
    chain: 14H
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median

val_dataloader_cfg:
    batch_size: 64
    
    
eval_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: test
    chain: 14H
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median
    
eval_dataloader_cfg:
    batch_size: 64

#eval_function_cfg:
    #_target_: src.sars_cov2_eval.sars_cov2_eval
    #chain: 14H
