defaults:
    - model_cfg: ExactGP
    #- logger_cfgs: Tensorboard
    - override hydra/launcher: submitit_slurm
    #- override hydra/sweeper: optuna

experiment_name: "train_exact_gp_template"
nodes: 1
hydra:
    run:
        dir: ./results/train/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

    sweep:
        dir: ./results/train/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

    #sweeper:
        #optuna_config:
          #direction: minimize
          #study_name: ${experiment_name}
          #storage: postgresql://pguser:s2i3pq31z5whnp04xgq4b45d4@txg-optape.cloud.llgrid.ll.mit.edu/postgres
          #n_trials: 50
          #n_jobs: 1
          #sampler: tpe
        #search_space:
          #model_cfg.lr:
            #type: float
            #low: 1e-4
            #high: 1e-1
            #log: true

          #model_cfg.num_epochs:
            #type: categorical
            #choices:
              #- 100
              #- 300
              #- 500
              #- 700
              #- 900

          #feat_cfg.pca_dim:
            #type: categorical
            #choices:
              #- 128
              #- 512
              #- 1024
              #- 2048


    launcher:
        partition: gaia
        tasks_per_node: 1
        nodes: ${nodes}
        constraint: xeon-g6
        timeout_min: 10000
        additional_parameters:
            {'gres':'gpu:volta:1'}
############
feat_cfg:
    _target_: src.models.feat_extraction.BertFeatExtractor
    model_config_file: /home/gridsan/groups/ai4bio_shared/models/in_house/bert/config.json
    feat_path: "/home/gridsan/groups/ai4bio_shared/models/in_house/heavychain_initialized_by_pfam_batchsize_2048_layers_24_lr_1e-5_hidsize_1024_intermediatesize_4096_attentionheads_16_epoch_5.ckpt"
    strict_reload: False
    variable_regions: True
    pca_dim: 1024

train_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: train
    chain: 14H
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median
    
train_dataloader_cfg:
    batch_size: 64
    shuffle: True
    
val_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: valid
    chain: 14H
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median
    
val_dataloader_cfg:
    batch_size: 64

