defaults:
    - model_cfg: BertPairedLM
    - logger_cfgs: Tensorboard
    - hydra/launcher: submitit_slurm

experiment_name: "eval_train_pairedLM_template"
nodes: 1
reload_checkpoint_path: "/home/gridsan/groups/ai4bio_shared/models/in_house/paired_initialized_by_pfam_batchsize_2048_layers_24_lr_1e-5_hidsize_1024_intermediatesize_4096_attentionheads_16_epoch_6.ckpt"

hydra:
    run:
        dir: ./results_bert_paired/train/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

    sweep:
        dir: ./results/train/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

    launcher:
        partition: gaia
        tasks_per_node: 2
        nodes: ${nodes}
        constraint: xeon-g6
        timeout_min: 10000
        additional_parameters:
            {'gres':'gpu:volta:2'}
############

trainer_cfg:
    max_epochs: 10
    gpus: 2
    num_nodes: ${nodes}
    distributed_backend: ddp

eval_set_cfg:
    _target_: src.datasets.PairedAntibodyBertLanguageModelingDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/oas/paired_for_LM_training/lmdb_pair_test" # paired only test data
    #data_path: "/home/gridsan/groups/ai4bio_shared/datasets/oas/paired_for_LM_training"  # test data for paired-only, light-only and heavy-only chains
    #data_path: "/home/gridsan/groups/ai4bio_shared/datasets/oas/paired_for_LM_training/lmdb_light_test" # light chain only test data
    #data_path: "/home/gridsan/groups/ai4bio_shared/datasets/oas/paired_for_LM_training/lmdb_heavy_test" # heavy chain only test data
    split: test
    tokenizer: "iupac"
    maxlen: 512
    
eval_dataloader_cfg:
    batch_size: 64