_target_: src.models.BertForValuePrediction
downstream_dropout: 0.3
downstream_hid_dim: 128
lr: 2.79551209035589e-05
loss_function: mse
model_config_file: /home/gridsan/groups/ai4bio_shared/models/in_house/bert_configs/bert/config.json
warmup_steps: 10000
