defaults:
    #- override hydra/launcher: submitit_slurm

experiment_name: "eval_gp_IgG"
reload_state_dict_path: /home/gridsan/LI25662/ML4Bio/biotransfer/results/train_titration_gifford_gp/train_titration_gifford_gp_all_1000e_/2021-09-08/20-25-52/4/GP_model_state_dict.pth

hydra:
    run:
        dir: ./results/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
############

model_cfg:
    _target_: src.models.ExactGP.GPSparse # use GPSparse when there is a large set of training data
    lr: 0.001
    num_epochs: 1000
    inducing_points: 2000

feat_cfg:
    _target_: src.models.feat_extraction.BertFeatExtractor
    model_config_file: /home/gridsan/groups/ai4bio_shared/models/in_house/bert_configs/bert/config_hiddenstate.json
    feat_path: "/home/gridsan/groups/ai4bio_shared/models/in_house/pfam_batchsize_2048_layers_24_lr_1e-5_hidsize_1024_intermediatesize_4096_attentionheads_16_epoch_13.ckpt"
    strict_reload: False
    variable_regions: False # True: use features only in the variable regions specified in the dataloader; False: use all the token embeddings
    feat_concat: False # True: concat token features; False: avg. token features
    pca_dim: null # int: perform pca dimensionality reduction to reduce the dimension to the specified value; null: do not perform pca

train_set_cfg:
    _target_: src.datasets.GiffordDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/gifford/rep1_rep2_splits"
    split: train
    
train_dataloader_cfg:
    batch_size: 32
    shuffle: True
    
eval_set_cfg:
    _target_: src.datasets.GiffordDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/gifford/rep1_rep2_splits"
    split: test
    
eval_dataloader_cfg:
    batch_size: 32
