defaults:
    #- override hydra/launcher: submitit_slurm

experiment_name: "train_gp_14L"
hydra:
    run:
        dir: ./results/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
############

model_cfg:
    _target_: src.models.ExactGP.GPRegressionModel
    lr: 0.001
    num_epochs: 1000
    inducing_points: null

feat_cfg:
    _target_: src.models.feat_extraction.BertFeatExtractor
    model_config_file: /home/gridsan/groups/ai4bio_shared/models/in_house/bert_configs/bert/config_hiddenstate.json
    feat_path: "/home/gridsan/groups/ai4bio_shared/models/in_house/pfam_batchsize_2048_layers_24_lr_1e-5_hidsize_1024_intermediatesize_4096_attentionheads_16_epoch_13.ckpt"
    strict_reload: False
    variable_regions: True
    feat_concat: True
    pca_dim: 1024

train_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: train
    chain: 14L
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median
    
train_dataloader_cfg:
    batch_size: 32
    shuffle: True
    
val_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: "/home/gridsan/groups/ai4bio_shared/datasets/AAbio_data/covid"
    split: valid
    chain: 14L
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median
    
val_dataloader_cfg:
    batch_size: 32

